apiVersion: v1
kind: Service
metadata:
  name: avsdevops-website
  namespace: avsdevops
  labels:
    app.kubernetes.io/name: avsdevops-website
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: avsdevops-website
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
